# Generated by Django 3.2.7 on 2021-09-10 09:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_alter_newsitem_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsItem',
            new_name='Post',
        ),
    ]
