# Generated by Django 3.2.7 on 2021-09-10 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_newsitem_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='news_item',
            new_name='post',
        ),
    ]
